### PR TITLE
Fix custom robot import for Isaac Sim 5.1

### PR DESCRIPTION
**Pull request by programessi**
## Summary

Thank you for maintaining BEHAVIOR-1K and the custom robot import workflow.

While testing the custom robot import tutorial on the current `main` branch with Isaac Sim 5.1, I ran into compatibility issues in `import_custom_robot.py`. The baseline quickstart works with the current 5.1 setup, but the custom robot import path fails on the Stretch tutorial config.

The first failure happens because `import_og_asset_from_urdf()` now requires `dataset_name`. After addressing that, a few additional updates were needed for Isaac Sim 5.1's URDF importer USD output and local pose APIs.

This PR proposes a small compatibility update for the custom robot import path:
- Pass `dataset_name="custom_dataset"` when importing custom robot URDFs.
- Update `XFormPrim` and local pose API usage for Isaac Sim 5.1.
- Handle quaternion convention conversion between Isaac Sim and OmniGibson utilities.
- Make USD post-processing compatible with Isaac Sim 5.1 geometry outputs.
- Add non-interactive smoke-test options to `robot_control_example.py`.

## Testing

- Current `main` quickstart with Isaac Sim 5.1: PASS
- Current `main` Stretch import: fails before this fix
  - `TypeError: import_og_asset_from_urdf() missing 1 required positional argument: 'dataset_name'`
- PR branch Stretch import: PASS
  - Generated `stretch_test.usda`
- PR branch imported Stretch control smoke test: PASS
  - `robot_control_example.py --robot stretch_test --scene empty --control-mode random --short-exec`
- Static checks:
  - `git diff --check origin/main..HEAD`
  - `py_compile` on changed Python files
  - grep check for local path or project-specific leftovers

### CODE REVIEW

**Comment by programessi** [comment]
Hi maintainers, thanks for taking a look when you have time. I noticed the Tests workflow is awaiting maintainer approval for this forked PR. Could someone approve the workflow run when convenient? Happy to address any review comments.

**Comment by programessi** [comment]
@wensi-ai @kmy17518  Sorry to ping directly. This PR is currently blocked because the Tests workflow for this forked PR is awaiting maintainer approval. Could one of you approve the workflow run when convenient? Thanks.

**Comment by programessi** [comment]
# PR #2287 Profiling Checks Comment

I looked into the failing Profiling checks.

The failed commands are from `.github/workflows/profiling.yml`:

- `python tests/benchmark/profiling.py -g -s Rs_int -r 1`
- `python tests/benchmark/profiling.py -r 1 -s house_single_floor`

These profiling paths load built-in `r1pro` / built-in scenes and do not exercise the files changed in this PR:

- `OmniGibson/omnigibson/examples/robots/import_custom_robot.py`
- `OmniGibson/omnigibson/examples/robots/robot_control_example.py`
- the URDF conversion path in `OmniGibson/omnigibson/utils/asset_conversion_utils.py`

I also found similar profiling failures on other recent PRs, including merged PRs:

- #2286 / #2283 / #2282 / #2281: `Profile: house_single_floor + 1 Robot` failed while the PRs were still merged.
- #2288: multiple Profiling jobs failed, including `Rs_int + 1 Robot`, `house_single_floor + 1 Robot`, and `Compile Profiling Report`.

Locally, the `Rs_int + 1 Robot` profiling command can reproduce an exit code 139 native crash even on a main checkout, with the crash stack in Omniverse/Isaac native plugins rather than a Python traceback.

So this looks like an existing/flaky self-hosted GPU profiling issue rather than a regression from this PR. Could a maintainer rerun the failed Profiling jobs or advise whether these profiling failures can be ignored for review? @wensi-ai @kmy17518

**Comment by yalcintur** [comment]
Hi @programessi, thanks a lot for this PR and for the detailed writeup!

We actually already had work in progress to fix the custom-robot import pipeline for Isaac Sim 5.1. I have combined that work with PR from our team member ([2215](https://github.com/StanfordVL/BEHAVIOR-1K/pull/2215)) and used parts of your PR, then validated the result by importing three different mobile manipulators end-to-end.

On the profiling checks, those failures are expected and unrelated to your change. There's a known regression in Isaac Sim 5.1 with GPU dynamics enabled, so it's not a problem here.

Really appreciate you digging into this and reporting it!

**Comment by programessi** [comment]
Thanks for the update and for validating the fix across multiple robots — glad the investigation was useful.

I noticed that parts of this PR were incorporated into the final fix. If possible, would you mind adding a reference to this PR (or co-author attribution) in the merged commit/PR for traceability? Completely understand if that’s not feasible with the current workflow.

Really appreciate the collaboration and the detailed feedback!




leo
***@***.***



        



         原始邮件
         
       
发件人：Yalcin Tur ***@***.***&gt;
发件时间：2026年6月30日 20:42
收件人：StanfordVL/BEHAVIOR-1K ***@***.***&gt;
抄送：Jansson Feng ***@***.***&gt;, Mention ***@***.***&gt;
主题：Re: [StanfordVL/BEHAVIOR-1K] Fix custom robot import for Isaac Sim 5.1 (PR #2287)



yalcintur left a comment (StanfordVL/BEHAVIOR-1K#2287)

Hi @programessi, thanks a lot for this PR and for the detailed writeup!

We actually already had work in progress to fix the custom-robot import pipeline for Isaac Sim 5.1. I have combined that work with PR from our team member (2215) and used parts of your PR, then validated the result by importing three different mobile manipulators end-to-end.

On the profiling checks, those failures are expected and unrelated to your change. There's a known regression in Isaac Sim 5.1 with GPU dynamics enabled, so it's not a problem here.

Really appreciate you digging into this and reporting it!

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications, keep track of coding agent tasks and review pull requests on the go with GitHub Mobile for iOS&nbsp;and Android. Download it today!
